### ISSUE TITLE
Menus get cut when authenticated

### ISSUE THREAD

**Issue by bmassot** [django-cms/django-cms#6652] opened 2019-03-15 13:32 UTC
### Summary
On my django CMS site, my pages use the {% show_menu %} and {% show_breadcrumb %} template tags. Some of them also have a {% show_menu_below_id %} tag to display a secondary menu.
Since I switched from django CMS 3.4.6 to 3.5.3, menus from show_breadcrumb and show_menu_below_id get cut when seen as an authenticated user. Calls to show_menu work fine though.

Anonymous visitors see menus and breadcrumb as expected, but as soon as a regular user authenticates, menu shown by show_menu is OK, but show_breadcrumb only displays the root page, and show_menu_below_id doesn't display any node. However the "admin" user can see all menus.

This was not happening with django CMS 3.4.6. With 3.4.6 this problem occurred only when in "edit" mode, which was still a bug but far less annoying.

### Environment

* Python version: 3.6.4
* Django version: 1.11.18
* django CMS version: 3.5.3

**Comment by tschale** [comment] 2019-04-05 11:41
I'm seeing the same issue, it might be a duplicate of #6428

**Comment by bmassot** [comment] 2019-06-05 13:58
#6429 seems to fix everything. Thank you!

**Comment by Aiky30** [comment] 2020-11-13 16:22
Fixed in 3.7.1: 

> Fixed a bug where the menu would render draft pages even if the page on the request was a public page. This happens when a user without change permissions requests edit mode.

https://github.com/django-cms/django-cms/blob/develop/CHANGELOG.rst#371-2019-11-26

**Closed by Aiky30** 2020-11-13 16:22 UTC
