### ISSUE TITLE
Can't delete model instances from admin list view that opens from the toolbar

### ISSUE THREAD

**Issue by creimers** [django-cms/django-cms#6495] opened 2018-08-29 17:00 UTC
### Summary

I can't delete model instances from the list view that opens from the toolbar. In the "normal" admin list view it does work. From the toolbar opened detailview of the model instance it also works.

### Expected behaviour

I'm expecting to be able to delete model instances from the toolbar list view.

### Actual behaviour

When confirming the deletion, the modal goes blank. The following error appears in the Javascript console:

```
Uncaught TypeError: e.match is not a function
    at HTMLAnchorElement.<anonymous> (bundle.toolbar.min.js:1)
    at HTMLAnchorElement.dispatch (bundle.toolbar.min.js:1)
    at HTMLAnchorElement.g.handle (bundle.toolbar.min.js:1)
```

### Environment

* Python version: 3.6
* Django version: 1.11
* django CMS version: 3.5.2

This is happending both in the Firefox and Chrome (latest at time of writing).

**Comment by vxsx** [comment] 2018-08-30 14:44
Could you provide an example project to reproduce?

**Comment by creimers** [comment] 2018-08-30 17:28
@vxsx You got it: https://github.com/creimers/djangocms-delete-error

**Comment by vxsx** [comment] 2018-08-31 07:45
So this happens due to the way browsers attach named inputs to forms. In your case form.action returns an input[name=action] instead of it's action property. I'll add a workaround

**Comment by creimers** [comment] 2018-08-31 08:43
I can confirm that it also fixes the problem for me. Thanks!

**Comment by Aiky30** [comment] 2020-12-08 16:56
Assuming fixed and closing this issue due to the feedback of fixed and seeing that it was released in 3.5.

**Closed by Aiky30** 2020-12-08 16:56 UTC
Labels: component: frontend, status: has patch
