### ISSUE TITLE
show_menu/show_breadcrumb do not find selected node in edit mode if you do not have permission to edit the current page

### ISSUE THREAD

**Issue by jdgoettsch** [django-cms/django-cms#6164] opened 2017-12-06 01:06 UTC
### Summary

The `show_menu` and `show_breadcrumb` template tags do not find the selected node for a page if you are in edit mode and do not have permission to edit the page. As a result, usage of the tags to show selected navigation cause nothing to be displayed.

### Expected behaviour

Using `show_menu` and `show_breadcrumb` to show page navigation should display the same output whether in edit mode or view mode, whether a user has permission to edit the current page or not.

### Actual behaviour

A user in edit mode, viewing a page they do not have permission to edit, receives no output from the `show_menu` and `show_breadcrumb` tags. Switching off edit mode or switching to a user with permission to edit the page causes the output to appear as expected.

### Environment

* Python version: 2.7
* Django version: 1.8.18
* django CMS version: 3.4.5

### Notes

If I use `{% show_menu 1 2 3 3 %}` (or similar) to display the menu from the home page, it displays as expected but does not mark the current node as "selected."

If I use `{% show_menu request.current_page.depth ... %}` to display the menu under the current page, nothing displays for a user in edit mode who does not have permission to edit the current page (presumably because `show_menu` is not finding the selected node).

Sorry I have not been able to debug this further.

**Comment by tschale** [comment] 2019-04-05 11:42
Might be a duplicate of/related to #6428

**Comment by Aiky30** [comment] 2020-11-13 16:24
Fixed in 3.7.1: 

> Fixed a bug where the menu would render draft pages even if the page on the request was a public page. This happens when a user without change permissions requests edit mode.

https://github.com/django-cms/django-cms/blob/develop/CHANGELOG.rst#371-2019-11-26

**Closed by Aiky30** 2020-11-13 16:24 UTC
