### ISSUE TITLE
Site breaks unless en-us is included in LANGUAGES

### ISSUE THREAD

**Issue by songproducer** [django-cms/django-cms#6360] opened 2018-05-04 05:32 UTC
### Summary

Site won't load when zh-hant and en is included. See below error message.

If en-us is used instead, it resolves the problem however all the existing English pages are lost as they are referenced as 'en'.

### Actual behaviour
Error when using en in languages.
```'LANGUAGE_CODE "%s" must have a matching entry in LANGUAGES' % settings.LANGUAGE_CODE
web_1  | django.core.exceptions.ImproperlyConfigured: LANGUAGE_CODE "en-us" must have a matching entry in LANGUAGES```

### Environment

* Python version: python3.5
* Django version: 1.8.18
* django CMS version:  3.5.2.2

**Comment by czpython** [comment] 2018-05-04 12:12
Hello @songproducer,
Can you post your settings?

**Comment by songproducer** [comment] 2018-07-07 15:35
Hi @czpython 

Here are my language settings:

```
LANGUAGE_CODE = 'en-us'
USE_I18N = True
LOCALE_PATHS = []

gettext_noop = lambda s: s

LANGUAGES = [
('en-us', gettext_noop('English')),
('zh-hant', gettext_noop('中文')),
]
```

I'm not migrating from one language to another, it's just a website with Chinese and English.

**Comment by davydany** [comment] 2018-12-11 00:51
@songproducer I experienced this same error and while Googling the issue, I saw this issues still opened. I fixed it.

Look in your `settings.py`... There is another LANGUAGES, like this:

```

LANGUAGES = (
    ## Customize this
    ('en', gettext('en')),
)
```

It must have come when you copied the code from Django CMS' documentation. Removing the 2nd one will make it work.

**Comment by victor-yunenko** [comment] 2021-09-16 13:38
It appears to be a configuration issue? Ie if `LANGUAGE_CODE` is set to `en-us` then yes, it has to be included in `LANGUAGES`. It's also not easy to change the `LANGUAGES` variable due to how `django-parler` works, but there isn't much we can do except maybe documenting it.

For now I'm assuming we can close this ticket. If you think that my assessment is incorrect, please feel free to submit additional reproduction details!

**Closed by victor-yunenko** 2021-09-16 13:38 UTC
Labels: needs more info
