### ISSUE TITLE
[BUG]Why I cannot find the static files while I already have them? Thanks.

### ISSUE THREAD

**Issue by zongbb1983** [django-cms/django-cms#8085] opened 2024-11-26 01:48 UTC
## Description
Why I cannot find the static files while I already have them? Thanks.

## Screenshots
When it runs, the result just like this：

![image](https://github.com/user-attachments/assets/c89539d0-e7f2-4b7a-a12f-70514dc6f33e)

and I've already flesh the temper file. 

The path shows in the browser is right and can find the source file. But just could not work. Please give me a help. Thanks! 

![image](https://github.com/user-attachments/assets/a794cbf1-54af-455f-ad7b-3da05f57288e)

--------------------------------------------------------------------------------------------------------

![image](https://github.com/user-attachments/assets/0bb728c1-d2f1-490a-993a-d2b08752d23b)

--------------------------------------------------------------------------------------------------------

![image](https://github.com/user-attachments/assets/f59bbfb6-422f-42ee-89a4-bff064674860)

--------------------------------------------------------------------------------------------------------

* [*] Yes, I want to help fix this issue and I will join the channel #pr-reviews on [the Discord Server](https://discord-pr-review-channel.django-cms.org) to confirm with the community that a PR is welcome.
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment] 2024-11-26 06:42
Duplicate of #8083:

* Update to the latest django-cms: `pip install -U django-cms`
* Clear browser cache
* run `./manage.py collectstatic` if not served through development server with `DEBUG = True`

Since you are using the development server what's its output when the browser tries to get static files?

**Closed by fsbraun** 2024-11-26 06:42 UTC

**Comment by zongbb1983** [comment] 2024-11-27 02:07
Still no reason... At last, I install it in a easy way, use the docker.......:)

**Comment by fsbraun** [comment] 2024-11-27 06:51
@zongbb1983 Did it work?
